### ISSUE TITLE
Astranot Kompleksi Sorunu

### ISSUE THREAD

**Issue by ahmetekrem** [FurkanS1821/KSP-TRYama#2]
Tr yama yapıldıktan sonra astronot kompleksinde crew yani mürettabat gözükmüyor. en-us yapıp denedim ve gözükmeye başladı. Sanırım yamadan kaynaklı. Bu soruna çözüm getirebilir misin?
Emeğin için çok teşekkür ederim.

**Comment by FurkanS1821** [comment]
Halledeceğim.
