### ISSUE TITLE
Her yerde 'autoLOC_....' yazıyor?

### ISSUE THREAD

**Issue by requizm** [FurkanS1821/KSP-TRYama#4]
Öncelikle teşekkürler. Yamayı daha önceden kullanmıştım. Bugün tekrardan yükledim, ancak her yazının yerinde '#autoLOC_sayino' yazıyor. Sürümüm 1.5.1.

**Comment by FurkanS1821** [comment]
Az önce hem yamayı, hem yamayı kurma yolunu değiştirdim. Tekrar indirip deneyebilirsiniz.

Olmazsa, dosyaları doğrulayıp tekrar deneyebilirsiniz.

**Comment by requizm** [comment]
Teşekkürler şimdi oldu.
